version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
  
  vaccine-bot:
    image: wayne900619/vaccine-bot:latest
    depends_on: [caddy]
    networks:
      - caddy
    labels:
      caddy: bot.txya.tk
      caddy.reverse_proxy: "{{upstreams https}}"

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}