name: publish image and deploy
on: push
jobs:
  publish-image:
    name: build binary than publish image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup go 1.16.5
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.5"

      - name: caching dependency
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: build binary file
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o ./vaccine-bot

      - name: publish image to docker hub
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          name: wayne900619/mr.coding-linebot
          username: wayne900619
          password: ${{ secrets.docker_password }}
          dockerfile: Dockerfile
  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    needs: publish-image
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            wget https://raw.githubusercontent.com/txya900619/vaccine-bot/master/docker-compose.yaml
            docker-compose up -d
